#!/usr/bin/env python3
"""
Cache Assistant — status line installer.

Adds the Cache Assistant tier + countdown row to the user's status line
*without clobbering* whatever they already have configured:

  * No existing status line  -> point statusLine.command straight at our script.
  * An existing status line   -> generate a wrapper that runs the user's original
                                 command first, then appends our row below it.
                                 The original command is preserved verbatim (and
                                 saved to a sidecar for --restore).
  * Already installed by us   -> idempotent refresh (re-resolve paths), original
                                 still preserved.

In all cases the previous settings.json is backed up first, and refreshInterval
is set to 1 so the countdown ticks once per second.

Usage:
  install_statusline.py [--settings PATH] [--statusline PATH] [--print] [--restore]
"""
import argparse
import json
import os
import sys
import time

MARKER = "cache-assistant-statusline.sh"  # our wrapper filename / sentinel


def installed_by_us(command):
    """True if `command` is one we installed — either the wrapper (identified by
    MARKER) or the direct `python3 '<plugin>/statusline/statusline.py'` form. Keys
    off the stable intra-plugin suffix rather than the plugin dir name, so it stays
    correct across version-dir changes and regardless of where the plugin lives.
    Prevents a re-run from mistaking our own command for a user's original and
    wrapping it."""
    c = (command or "").replace("\\", "/")
    return (MARKER in c) or ("statusline/statusline.py" in c)


def resolve_our_statusline(explicit):
    if explicit:
        return os.path.abspath(explicit)
    root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if root:
        cand = os.path.join(root, "statusline", "statusline.py")
        if os.path.exists(cand):
            return os.path.abspath(cand)
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.abspath(os.path.join(here, "..", "..", "statusline", "statusline.py"))


def load_json(path, default):
    try:
        with open(path) as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return default


def atomic_write_json(path, data):
    tmp = "{}.{}.tmp".format(path, os.getpid())
    with open(tmp, "w") as fh:
        json.dump(data, fh, indent=2)
        fh.write("\n")
    os.replace(tmp, path)


def build_wrapper(inner_command, our_statusline):
    """A POSIX-sh wrapper: run the user's original command, then our row."""
    inner_escaped = inner_command.replace("'", "'\\''")
    return (
        "#!/bin/sh\n"
        "# {marker} — generated by Cache Assistant. Non-destructive wrapper:\n"
        "# it runs your original status line command, then appends the cache row.\n"
        "input=$(cat)\n"
        "orig=$(printf '%s' \"$input\" | ( eval '{inner}' ) 2>/dev/null)\n"
        "mine=$(printf '%s' \"$input\" | python3 '{ours}')\n"
        "[ -n \"$orig\" ] && printf '%s\\n' \"$orig\"\n"
        "printf '%s\\n' \"$mine\"\n"
    ).format(marker=MARKER, inner=inner_escaped, ours=our_statusline.replace("'", "'\\''"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--settings", default=os.path.join(
        os.path.expanduser("~"), ".claude", "settings.json"))
    ap.add_argument("--statusline", default=None)
    ap.add_argument("--print", dest="dry", action="store_true",
                    help="show what would change without writing")
    ap.add_argument("--restore", action="store_true",
                    help="restore the status line saved before install")
    args = ap.parse_args()

    settings_path = os.path.abspath(args.settings)
    settings_dir = os.path.dirname(settings_path)
    cadir = os.path.join(settings_dir, "cache-assistant")
    wrapper_path = os.path.join(cadir, MARKER)
    sidecar_path = os.path.join(cadir, "original-statusline.json")
    our_sl = resolve_our_statusline(args.statusline)

    settings = load_json(settings_path, {})
    cur = settings.get("statusLine")

    if args.restore:
        original = load_json(sidecar_path, {"_missing": True})
        if original.get("_missing"):
            print("Nothing to restore (no saved original status line).")
            return 0
        if original in ({}, None):
            settings.pop("statusLine", None)
        else:
            settings["statusLine"] = original
        if not args.dry:
            atomic_write_json(settings_path, settings)
        print("Restored the original status line.")
        return 0

    already_ours = isinstance(cur, dict) and installed_by_us(cur.get("command"))

    # Determine the "inner" (user's original) command to preserve.
    if already_ours:
        saved = load_json(sidecar_path, {})
        inner = (saved or {}).get("command") if isinstance(saved, dict) else None
    else:
        inner = None
        if isinstance(cur, dict) and cur.get("type") == "command" and cur.get("command"):
            inner = cur.get("command")
        # Save the true original once, for idempotent re-runs and --restore.
        if not os.path.exists(cadir):
            os.makedirs(cadir, exist_ok=True)
        atomic_write_json(sidecar_path, cur if cur is not None else {})

    os.makedirs(cadir, exist_ok=True)

    # Preserve unrelated statusLine fields (e.g. padding) from a dict config.
    preserved = {}
    if isinstance(cur, dict):
        for k in ("padding", "hideVimModeIndicator"):
            if k in cur:
                preserved[k] = cur[k]

    if inner:
        wrapper = build_wrapper(inner, our_sl)
        if not args.dry:
            with open(wrapper_path, "w") as fh:
                fh.write(wrapper)
            os.chmod(wrapper_path, 0o755)
        new_command = "sh '{}'".format(wrapper_path.replace("'", "'\\''"))
        mode = "merged (wrapped your existing status line)"
    else:
        new_command = "python3 '{}'".format(our_sl.replace("'", "'\\''"))
        mode = "installed (no prior status line found)"

    new_sl = dict(preserved)
    new_sl.update({"type": "command", "command": new_command, "refreshInterval": 1})

    if args.dry:
        print("DRY RUN — no files written.\n")
        print("mode:            ", mode)
        print("settings.json:   ", settings_path)
        print("our statusline:  ", our_sl)
        if inner:
            print("preserved inner: ", inner)
            print("wrapper script:  ", wrapper_path)
        print("\nnew statusLine block:")
        print(json.dumps(new_sl, indent=2))
        return 0

    # Back up settings.json before writing.
    if os.path.exists(settings_path):
        bak = "{}.cache-assistant.bak.{}".format(settings_path, int(time.time()))
        try:
            with open(settings_path) as a, open(bak, "w") as b:
                b.write(a.read())
        except OSError:
            bak = "(backup failed)"
    else:
        bak = "(no prior settings.json)"

    settings["statusLine"] = new_sl
    if not os.path.isdir(settings_dir):
        os.makedirs(settings_dir, exist_ok=True)
    atomic_write_json(settings_path, settings)

    print("Cache Assistant status line {}.".format(mode))
    print("  settings.json: {}".format(settings_path))
    print("  backup:        {}".format(bak))
    if inner:
        print("  preserved your original command inside: {}".format(wrapper_path))
    print("  refreshInterval set to 1 (1-second countdown).")
    print("\nStart or restart Claude Code to see the cache row.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
